name: busy_reader
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_route: ^7.8.3
  auto_route_generator: ^7.3.1
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  connectivity_plus: ^4.0.1
  http: ^1.0.0
  mockito: ^5.4.2
  internet_connection_checker: ^1.0.0+1

  build_runner: ^2.4.6
  flutter_gen_runner:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/colors/
    - assets/icons/
    - assets/json/
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf

flutter_gen:
  output: lib/res/assets/
  style: camel-case
  colors:
    inputs:
      - assets/colors/colors.xml
  integrations:
    flutter_svg: true